name: checklist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.3.3
  provider: ^6.1.5+1
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  cbl: ^3.6.0+2
  cbl_flutter: ^3.3.5
  cbl_flutter_ce: ^3.5.1
  connectivity_plus: ^7.0.0
  workmanager: ^0.9.0+3
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
